[project]
name = "x2a-convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "ipdb>=0.13.13",
    "langchain>=0.3.27",
    "langchain-anthropic>=0.3.20",
    "langchain-community>=0.3.27",
    "langchain-openai>=0.3.33",
    "langgraph>=0.6.7",
    "tree-sitter>=0.23.0",
    "tree-sitter-ruby>=0.23.0",
    "tree-sitter-json>=0.23.0",
]

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
    "pytest>=8.3.0",
    "ruff>=0.13.2",
]
