[project]
name = "x2a-convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-anthropic>=0.3.20",
    "langgraph>=0.6.7",
]

[dependency-groups]
dev = [
    "langchain>=0.3.27",
    "langgraph>=0.6.7",
    "ruff>=0.13.2",
]
