[project]
name = "x2a-convertor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "langchain-anthropic>=0.3.20",
    "langgraph>=0.6.7",
]

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-google-vertexai>=2.1.2",
    "langgraph>=0.6.7",
    "ruff>=0.13.2",
]
