apiVersion: tower.ansible.com/v1beta1
kind: JobTemplate
metadata:
  name: nginx_multisite_deploy
spec:
  name: nginx_multisite_deploy
  job_type: run
  playbook: playbooks/nginx_multisite_deploy.yml
  inventory: Default

  description: Deploy nginx_multisite role


  role_name: nginx_multisite


